services:

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: Nexila
      MONGO_INITDB_ROOT_PASSWORD: Nexila@123
      MONGO_INITDB_DATABASE: crm

    command: ["--auth"]

    volumes:
      - mongo_data:/data/db

  backend:
    image: mahesh9030/nexila-crm-backend:latest

    container_name: backend

    restart: always

    depends_on:
      - mongo

    env_file:
      - ./backend/.env

    ports:
      - "5000:5000"

    command: >
      sh -c "node server.js"

  frontend:
    image: mahesh9030/nexila-crm-frontend:latest

    container_name: template

    restart: always

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  mongo_data: